### ISSUE TITLE
No read_word()?

### ISSUE THREAD

**Issue by seplee** [rdagger/micropython-sgtl5000#5]
Hey! Great work on this module.

The function vag_ramp() [makes a call to self.read_word()](https://github.com/rdagger/micropython-sgtl5000/blob/main/sgtl5000.py#L1146) but read_word() doesn't exist in the latest version of sgtl5000.py.

read_word() was deleted in [this commit](https://github.com/rdagger/micropython-sgtl5000/commit/be9ac74232082807b47ca6b2d9703ab35f481f22).

Should I use a different function?

Also, I noticed that although there is an example of the sgtl5000 module in the [micropython quick reference for mimxr](https://docs.micropython.org/en/latest/mimxrt/quickref.html), sgtl5000 is not included in the latest version of micropython. 
What gives? 😉

**Comment by rdagger** [comment]
I switched course on the project that was going to use the sgtl5000 so I haven't worked on this code since Robert's update.  Looks like he renamed read_word() to \_\_setitem\_\_()

I can't speak for the Micropython team, but there's a thread on the MicroPython forum called Teensy 4.0 & 4.1 under Boards Running MicroPython/Other Boards.  Mike Teachman or RobertHH will probably answer any questions relating to the sgtl5000 there.  They're great guys and super helpful.

**Comment by seplee** [comment]
Roger that. Thank you for your help and for your awesome driver!
